# Generated by Django 4.1.7 on 2023-03-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("curp", models.CharField(max_length=45)),
                ("respuesta", models.CharField(max_length=300, null=True)),
                ("descripcion", models.CharField(max_length=900)),
                ("numSeguimiento", models.CharField(max_length=20, null=True)),
                ("accion_denuncia", models.CharField(max_length=50, null=True)),
                ("fecha_hechos", models.CharField(max_length=20, null=True)),
                ("hora_hechos", models.CharField(max_length=20, null=True)),
                ("lugar_hechos", models.CharField(max_length=200, null=True)),
                ("testigos", models.CharField(max_length=400, null=True)),
                ("denuncia_anonima", models.BooleanField(default=False, null=True)),
                ("telefono_denunciante", models.CharField(max_length=20, null=True)),
                ("correo_denunciante", models.CharField(max_length=200, null=True)),
                ("firma", models.ImageField(null=True, upload_to="firmas")),
                ("tipodenuncia", models.CharField(max_length=70, null=True)),
                ("nombredenunciado", models.CharField(max_length=100, null=True)),
                ("calle_denuncia", models.CharField(max_length=100, null=True)),
                ("entreCalleUno_denuncia", models.CharField(max_length=100, null=True)),
                ("entreCalleDos_denuncia", models.CharField(max_length=100, null=True)),
                ("municipio_denunciado", models.TextField(max_length=45, null=True)),
                ("codigoPostal_denunciado", models.TextField(max_length=45, null=True)),
                ("colonia_denunciado", models.TextField(max_length=45, null=True)),
                ("calle_denunciado", models.TextField(max_length=45, null=True)),
                ("numExterior_denunciado", models.TextField(max_length=10, null=True)),
                ("numInterior_denunciado", models.TextField(max_length=45, null=True)),
                ("municipio_denunciador", models.TextField(max_length=45, null=True)),
                (
                    "codigoPostal_denunciador",
                    models.TextField(max_length=45, null=True),
                ),
                ("colonia_denunciador", models.TextField(max_length=45, null=True)),
                ("calle_denunciador", models.TextField(max_length=45, null=True)),
                ("numExterior_denunciador", models.TextField(max_length=10, null=True)),
                ("numInterior_denunciador", models.TextField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="estatusdenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=45)),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="lugarDenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=100)),
                ("entreCalleUno", models.CharField(max_length=100)),
                ("entreCalleDos", models.CharField(max_length=100)),
                ("descripcion", models.TextField(null=True)),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.denuncia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="evidencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200, null=True)),
                ("url", models.TextField(max_length=500)),
                ("image", models.ImageField(blank=True, upload_to="fotos")),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.denuncia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="domicilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("municipio", models.TextField(max_length=45)),
                ("codigoPostal", models.TextField(max_length=45)),
                ("colonia", models.TextField(max_length=45)),
                ("calle", models.TextField(max_length=45)),
                ("numExterior", models.IntegerField()),
                ("numInterior", models.TextField(max_length=45, null=True)),
                (
                    "denuncia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncia_images",
                        to="frontend.denuncia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="denuncia",
            name="estatus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.estatusdenuncia",
            ),
        ),
    ]
