# Generated by Django 4.1.7 on 2023-03-02 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numSeguimiento", models.CharField(max_length=15)),
                ("nombre", models.CharField(max_length=45)),
                ("apellidoPaterno", models.CharField(max_length=45)),
                ("curp", models.CharField(max_length=45)),
                ("respuesta", models.CharField(max_length=300, null=True)),
                ("descripcion", models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name="estatusdenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=45)),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="lugarDenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=100)),
                ("entreCalleUno", models.CharField(max_length=100)),
                ("entreCalleDos", models.CharField(max_length=100)),
                ("descripcion", models.TextField(null=True)),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.denuncia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="evidencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(max_length=500)),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.denuncia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="domicilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("municipio", models.TextField(max_length=45)),
                ("codigoPostal", models.TextField(max_length=45)),
                ("colonia", models.TextField(max_length=45)),
                ("calle", models.TextField(max_length=45)),
                ("numExterior", models.IntegerField()),
                ("numInterior", models.TextField(max_length=45, null=True)),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="frontend.denuncia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="denuncia",
            name="estatus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.estatusdenuncia",
            ),
        ),
    ]
