# Generated by Django 4.1.7 on 2023-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denuncia",
            name="descripcion",
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="firma",
            field=models.TextField(null=True),
        ),
    ]
