# Generated by Django 4.1.7 on 2023-03-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='denuncia',
            fields=[
                ('numSeguimiento', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidoPaterno', models.CharField(max_length=45)),
                ('curp', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.TextField(max_length=45)),
                ('codigoPostal', models.TextField(max_length=45)),
                ('colonia', models.TextField(max_length=45)),
                ('calle', models.TextField(max_length=45)),
                ('numExterior', models.IntegerField(max_length=45)),
                ('numInterior', models.TextField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='evidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='lugarDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('entreCalleUno', models.CharField(max_length=100)),
                ('entreCalleDos', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
