# Generated by Django 4.1.7 on 2023-03-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencias",
            name="descripcion",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
