# Generated by Django 4.1.7 on 2023-03-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0002_evidencias_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencias",
            name="image",
            field=models.ImageField(blank=True, upload_to="fotos"),
        ),
    ]
