# Generated by Django 4.1.7 on 2023-03-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0004_alter_domicilio_denuncia"),
    ]

    operations = [
        migrations.AddField(
            model_name="denuncia",
            name="accion_denuncia",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="correo_denunciante",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="denuncia_anonima",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="fecha_hechos",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="firma",
            field=models.ImageField(null=True, upload_to="firmas"),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="hora_hechos",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="lugar_hechos",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="telefono_denunciante",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="denuncia",
            name="testigos",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="estatus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.estatusdenuncia",
            ),
        ),
        migrations.AlterField(
            model_name="denuncia",
            name="numSeguimiento",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
